SELECT
    CONCAT(CASE WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 01 AND 03 
        THEN 1
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 04 AND 06
        THEN 2
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 07 AND 09 
        THEN 3
    ELSE 4
    END, 'Q') AS QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;