WITH RECURSIVE num (HOUR) AS
(
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM num WHERE HOUR < 23
)

SELECT num.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM num
LEFT JOIN ANIMAL_OUTS A
    ON num.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR;