SELECT H.FLAVOR AS FLAVOR
FROM FIRST_HALF H
JOIN ICECREAM_INFO I
    ON H.FLAVOR = I.FLAVOR
WHERE I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY H.FLAVOR
    HAVING SUM(TOTAL_ORDER) > 3000
ORDER BY SUM(TOTAL_ORDER) DESC;